name: Build and upload package

on: [push, pull_request]

jobs:
  build-and-upload:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: python -m pip install wheel

      - name: Build distributions
        shell: bash -l {0}
        run: |
          python setup.py sdist --dist-dir dist
          python -m pip wheel . --wheel-dir dist --no-deps

      - name: Publish package to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_upload_token }}
